name: 单列车数据库
on:
  schedule:
    - cron: '0 7 * * *'  # UTC 07:00 = UTC+8 15:00
  workflow_dispatch:    # 支持手动触发

jobs:
  generate-csv:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 必须赋予写入权限

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置Python环境并缓存整个环境
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'  # 自动缓存pip依赖

      # 3. 缓存整个Python环境（包括site-packages）
      - name: Cache Python env
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            /opt/hostedtoolcache/Python/3.11*/x64/lib/python3.11/site-packages
          key: ${{ runner.os }}-python-3.11-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-3.11-

      # 4. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. 创建datasets目录
      - name: Create datasets folder
        run: mkdir -p dataset

      # 6. 运行脚本（输出到datasets/YYYYMMDD.csv）
      - name: Run main.py
        run: python main_first.py

      # 7. 强制提交所有变更
      - name: Force Commit to datasets/
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-Update: 2025_G5003.csv"
          skip_dirty_check: true  # 强制提交
          branch: main
          file_pattern: 'datasets/*'
