name: Daily CSV Export (UTC+8 15:00)
on:
  schedule:
    - cron: '30 5 * * *'  # UTC 07:00 = UTC+8 15:00
  workflow_dispatch:      # 支持手动触发

jobs:
  generate-csv:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # 必须赋予写入权限

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整提交历史

      # 2. 设置Python环境
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'    # 启用pip缓存

      # 3. 缓存整个Python环境
      - name: Cache Python environment
        uses: actions/cache@v3
        id: cache-python
        with:
          path: |
            ~/.cache/pip
            /opt/hostedtoolcache/Python/3.11*/x64/lib/python3.11/site-packages
          key: ${{ runner.os }}-python-${{ hashFiles('requirements.txt') }}-${{ hashFiles('main_first.py') }}
          restore-keys: |
            ${{ runner.os }}-python-

      # 4. 安装依赖（仅在缓存未命中时执行）
      - name: Install dependencies
        if: steps.cache-python.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          fi

      # 5. 创建dataset目录
      - name: Create dataset folder
        run: mkdir -p dataset

      # 6. 计算两天前的日期
      - name: Calculate date minus 2 days
        id: date_calc
        run: |
          # 计算两天前的日期（UTC时间）
          MINUS_TWO_DAYS=$(date -u -d "-2 days" +'%Y%m%d')
          echo "MINUS_TWO_DAYS=$MINUS_TWO_DAYS" >> $GITHUB_OUTPUT
          echo "文件名将为: dataset/${MINUS_TWO_DAYS}_G339.csv"

      # 7. 运行main_first.py脚本
      - name: Run main_first.py
        run: python main_first.py

      # 8. 配置Git用户信息
      - name: Setup Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # 9. 自动提交生成的CSV文件到dataset目录
      - name: Commit and push CSV file
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 使用计算出的日期
          CSV_FILE="dataset/${{ steps.date_calc.outputs.MINUS_TWO_DAYS }}_G339.csv"
          
          # 检查文件是否存在
          if [ -f "$CSV_FILE" ]; then
            git add "$CSV_FILE"
            git commit -m "Auto-Update: ${{ steps.date_calc.outputs.MINUS_TWO_DAYS }}_G339.csv"
            git push https://$GH_TOKEN@github.com/${{ github.repository }}.git main
            echo "✅ CSV文件已提交: $CSV_FILE"
          else
            echo "❌ 文件未生成: $CSV_FILE"
            echo "检查main_first.py是否正确输出到dataset/目录"
            echo "dataset目录内容:"
            ls -la dataset/ || echo "dataset目录不存在"
            exit 1
          fi
