name: Daily CSV Export (UTC+8 15:00)
on:
  schedule:
    - cron: '0 7 * * *'  # UTC 7:00 = UTC+8 15:00 [2,6](@ref)
  workflow_dispatch:      # 支持手动触发

jobs:
  generate-csv:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # 必须赋予写入权限 [2](@ref)

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置 Anaconda 环境
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.11"
          activate-environment: "auto-env"
          auto-update-conda: true

      # 3. 创建数据集目录
      - name: Create datasets folder
        run: mkdir -p datasets

      # 4. 安装依赖（若需 requirements.txt）
      - name: Install dependencies
        shell: bash -l {0}  # 激活 Conda 环境
        run: |
          conda install -c conda-forge pandas -y
          pip install -r requirements.txt  # 可选

      # 5. 运行脚本（输出到 datasets/YYYYMMDD.csv）
      - name: Run main.py
        shell: bash -l {0}
        run: python main.py

      # 6. 强制提交所有变更（无论文件是否修改）
      - name: Force Commit to datasets/
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-Update: $(date -u +'%Y%m%d').csv"
          skip_dirty_check: true  # 核心：跳过变更检查 [10](@ref)
          branch: main
          file_pattern: 'datasets/*'  # 仅提交 datasets 目录 [2](@ref)
